app:
  auth:
    tokenSecret:
    tokenExpirationMsec: 864000000
  oauth2:
    authorizedRedirectUris:
      - http://localhost:3000/oauth2/redirect

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id:
            client-secret:
            redirectUri:
            scope:
              - email
              - profile

